config/routes.rb
Rails.application.routes.draw do
 
  get '/workouts/type_exercises' => "workouts#type_exercises"
  resources :exercises
  resources :workouts
  resources :types
  resources :users_workouts
  devise_for :users
  root 'workouts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_and_belongs_to_many :types

  has_many :exercises_workouts
  has_many :workouts, through: :exercises_workouts, dependent: :destroy
  
  belongs_to :user
  
  has_one_attached :video
  validate :correct_video_mime_type
  
  validates :name, :description, :video, presence: true

  private

  def correct_video_mime_type
    if video.attached? && !video.content_type.in?(%w(video/mp4))
      errors.add(:video, 'Must be a Video')
    end
  end
  
end

app/models/exercises_workout.rb
class ExercisesWorkout < ApplicationRecord
  belongs_to :exercise
  belongs_to :workout
end

app/models/type.rb
class Type < ApplicationRecord
	has_and_belongs_to_many :exercises
  
  def self.search(search)
    if search
      #Type.where("name LIKE ?", "%" + search + "%")
      type = Type.find_by(name: search)
    else
      Type.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exercises
  
  # to get the trainer workouts
  #has_many :trainer_workouts, class_name: 'Workout', foreign_key: 'user_id'
  
  # to find normal users workout
  has_many :users_workouts
  has_many :workouts, through: :users_workouts , dependent: :destroy
end

app/models/users_workout.rb
class UsersWorkout < ApplicationRecord
  belongs_to :user
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
  # to find normal users workout
  has_many :users_workouts
  has_many :users, through: :users_workouts , dependent: :destroy

  #belongs_to :trainer, class_name: 'User', foreign_key: 'user_id'

  has_many :exercises_workouts
  has_many :exercises, through: :exercises_workouts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def is_trainer?
    current_user.try(:admin?)
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_trainer, :except => [:index, :show]
  before_action :validate_exercise_id, :except => [:index, :new, :create]

  def index
    @exercise = Exercise.all
  end

  def show
  end
  
  def new
    @type = Type.all
    @exercise = current_user.exercises.build
  end
 
  def edit
  end
  
  def update
    if @exercise.update(exercise_params)
      redirect_to exercises_path
    else
      render 'edit'
    end
  end

  def create
    @exercise = current_user.exercises.build(exercise_params)
    @exercise.video.attach(params[:exercise][:video])
    if @exercise.save
      redirect_to exercises_path
    else
      render 'new'
    end
  end

  def destroy
    @exercise.destroy
 
    redirect_to exercises_path
  end
 

  private
  
  def validate_exercise_id
    @exercise = Exercise.find_by(id: params[:id])
    if @exercise.blank?
      flash[:success] = "Not a valid Path"
      redirect_to exercises_path 
    end
  end

  def authenticate_trainer
    redirect_to exercises_path unless current_user && is_trainer?
  end
  
  def exercise_params
    params.require(:exercise).permit(:name, :description, :video, type_ids:[])
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_trainer
  before_action :validate_type_id, :except => [:index, :new, :create]  

  def index
    @type = Type.search(params[:search])
    if params[:search] && !@type.blank?
      redirect_to type_path(@type)
    else
      flash[:success] = "Not a valid Path" unless params[:search].blank?
      @type = Type.all
    end
  end
  
  def show
  end
  
  def new
    @type = Type.new
  end
 
  def edit
  end
  
  def update
    if @type.update(type_params)
      redirect_to types_path
    else
      render 'edit'
    end
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render 'new'
    end
  end

  def destroy
    @type.destroy
    redirect_to types_path
  end

  
  private

  def validate_type_id
    @type = Type.find_by(id: params[:id])
    redirect_to types_path if @type.blank?
  end
  
  def authenticate_trainer
    redirect_to workouts_path unless current_user && is_trainer?
  end
  
  def type_params
    params.require(:type).permit(:name, :description, :search)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_workouts_controller.rb
class UsersWorkoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_trainer
  
  def new
    @workouts = current_user.workouts
    @users = User.where(:admin => false)
  end

  def create 
    @user = User.find(params[:user])
    redirect_to workouts_path if @user.blank?
    @workout_ids = params[:user_workout][:workout_ids]
    @workout_ids.each do |w|
      next if w.blank?
      @user_workout = @user.users_workouts.new(workout_id: w)
      @user_workout.save
    end
    @url = workouts_url
    WorkoutMailer.with(user: @user).new_workout_email(@url).deliver_now

    redirect_to workouts_path      
  end

  private

  def authenticate_trainer
    redirect_to workouts_path unless current_user && is_trainer?
  end

  def user_workout_params
    params.require(:user_workout).permit(workout_ids:[])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_trainer, :except => [:index, :show]
  before_action :validate_workout_id, :except => [:index, :new, :create, :type_exercises]  
  
  def index
    if current_user.admin?
      #@workout = Workout.all
      @workout  = Workout.paginate(:page => params[:page], :per_page=>5)
    else 
      @workout = current_user.workouts
    end
  end

  def show
  end

  def new
    @types = Type.all
    @workout = current_user.workouts.build
    @exercises = Exercise.all
  end

  def edit
    @types = Type.all
    @exercises = Exercise.all
  end

  def update
    if @workout.update(workout_params)
      redirect_to workouts_path
    else
      render 'edit'
    end
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to workouts_path
    else
      render 'new'
    end
  end

  def destroy   
    @workout.destroy
    redirect_to workouts_path
  end

  def type_exercises
    if params[:type_id].present?
      @type = Type.find_by(id: params[:type_id])
      @exercises = @type.exercises
    else
      @exercises = Exercise.all
    end
    
    respond_to do |format|
      format.html
      format.json { render json: { "exercises" => @exercises} }
    end
  end

  private

  def validate_workout_id
    @workout = Workout.find_by(id: params[:id])
    redirect_to workouts_path if @workout.blank?
  end

  def authenticate_trainer
    redirect_to workouts_path unless current_user && is_trainer?
  end

  def workout_params
    params.require(:workout).permit(:name, :description, exercise_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_workouts_helper.rb
module UsersWorkoutsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_with(model: @exercise, local: true) do |form| %>
 
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@exercise.errors.count, "error") %> prohibited
        this exercise from being saved:
      </h2>

      <ul>
        <% @exercise.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :video %><br>
    <%= form.file_field :video %>
  
  </p>
  <p>
    <video controls true width="320" height="240"></video>
  </p>
  <h1>Listing Types</h1>

  <div>
    <%= collection_check_boxes :exercise, :type_ids, Type.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div> 
  
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/exercises/edit.html.erb
<h1>Edit Exercise</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<nav class="navbar navbar-light bg-light">
  <li>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
    <% else %>
     <%= link_to('Login', new_user_session_path) %>  
    <% end %>
  </li>
</nav>

<nav class="navbar navbar-light bg-light">
  <li>
    <%= link_to 'All Workouts', workouts_path %>
  </li>
</nav>

<%if current_user.admin? %>
<nav class="navbar navbar-light bg-light">
  <li>
    <%= link_to 'New exercise', new_exercise_path %>
  </li>
</nav>

<nav class="navbar navbar-light bg-light">
  <li>
    <%= link_to 'All Types', types_path %>
  </li>
</nav>

<nav class="navbar navbar-light bg-light">
  <li>
    <%= link_to 'Assign Workout to user', new_users_workout_path %>
  </li>
</nav>

<% end %>

<h1>Listing Exericses</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Types</th>
    <th colspan="3"></th>
  </tr>
  <% @exercise.each do |exercise| %>
    <tr>
      <td><%= exercise.name %></td>

      <td><%= exercise.description %></td>

      <td> <% exercise.types.each do |type| %>
          <%= type.name %>
        <% end %></td>

      <td><%= link_to 'Show', exercise_path(exercise) %></td>

      <%if current_user.admin? %>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
      
        <td><%= link_to 'Destroy', exercise_path(exercise),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</table>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

  <%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @exercise.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @exercise.description %>
</p>

<p>
  <strong>Types:</strong> 
  
  <% @exercise.types.each do |type| %>
      <%= type.name %>
  <% end %>
</p>

<p>
  <% if @exercise.video.previewable? %>
    
    <%= video_tag "#{url_for(@exercise.video)}", size: '420x240', :controls => true if @exercise.video.attached? %>
  
  <% end %>
  
</p>

<%= link_to 'Back', exercises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%- if flash.any? %>
      <%- flash.keys.each do |flash_key| %>
        <%- next if flash_key.to_s == 'timedout' %>
        <div class="alert-message <%= flash_key %>">
        <%= flash.discard(flash_key) %>
        </div>
      <%- end %>
    <%- end %>
    
    <%= yield %>
   
  </body>
</html>

app/views/types/_form.html.erb
<%= form_with(model: @type, local: true) do |form| %>
 
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@type.errors.count, "error") %> prohibited
        this Type from being saved:
      </h2>
      <ul>
        <% @type.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :description %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/types/edit.html.erb
<h1>Edit Type</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<nav class="navbar navbar-light bg-light">
  <% if user_signed_in? %>
    <li>
     <%= link_to('Logout', destroy_user_session_path, method: :delete) %>  
    </li>
  <% else %>
    <li>
     <%= link_to('Login', new_user_session_path) %>  
    </li>
  <% end %>
</nav>

<%if current_user.admin? %>
  <nav class="navbar navbar-light bg-light">
    <li>
      <%= link_to 'All Exercises', exercises_path %>
    </li>
  </nav>

  <nav class="navbar navbar-light bg-light">
    <li>
      <%= link_to 'All Types', types_path %>
    </li>
  </nav>

  <nav class="navbar navbar-light bg-light">
    <li>
      <%= link_to 'Assign Workout to user', new_users_workout_path %>
    </li>
  </nav>

  <nav class="navbar navbar-light bg-light">
    <li>
      <%= link_to 'New Type', new_type_path %>
    </li>
  </nav>

  <nav class="navbar navbar-light bg-light">
    <li>
      <%= link_to 'New Workout', new_workout_path %>
    </li>
  </nav>
<% end -%>
  

<h1>Listing Types</h1>

<%= form_tag types_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  
<table>
  <tr>
    <th>Title</th>  
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
  <% @type.each do |type| %>
    <tr>
      <td><%= type.name %></td>
      <td><%= type.description %></td>
      <td><%= link_to 'Show', type_path(type) %></td>
      <%if current_user.admin? %>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type_path(type),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</table>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @type.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @type.description %>
</p>

<p> 
  <% @type.exercises.each do |ex| %>
        <li>
          <%= ex.name %>
          <%= video_tag url_for(ex.video), size: '150x150', :controls => true if ex.video.attached? %>
        </li>
  <% end %>
</p>

<%= link_to 'Back', types_path %>

app/views/users_workouts/new.html.erb
<h1>Assign Workout to User</h1>

<%= form_with scope: :user_workout, url: users_workouts_path, local: true do |form| %>

  <h1>Listing Users</h1>
  
  <div>
    
    <%=  select_tag "user", options_from_collection_for_select(@users, "id", "email")%>

  </div> 

  <h1>Listing Workouts</h1>
  
  <div>
    <%= collection_check_boxes :user_workout, :workout_ids, Workout.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div> 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/workouts/_form.html.erb
<nav class="navbar navbar-light bg-light">
<%= form_with(model: @workout, local: true) do |form| %>
 
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@workout.errors.count, "error") %> prohibited
        this workout from being saved:
      </h2>
      <ul>
        <% @workout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :description %>
  </p>

  <div>
    <p>Please select the Type :- 
    <%=  select_tag "type", options_from_collection_for_select(@types, "id", "name"), :include_blank => true %>
    </p>
  </div> 

  <div>
    <%# byebug %>

    <p>Please select the Exercises :- </p>
    <div id = "checkbox_ids">
      <%= collection_check_boxes :workout, :exercise_ids, @exercises, :id, :name do |b| %>
        <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
        </div>
      <% end %>
    </div>
  </div> 
  
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
</nav>

app/views/workouts/edit.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <h1>Edit Workout</h1>
</nav>
 
<%= render 'form' %>
 
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <%if current_user.admin? %>
        <nav class="navbar navbar-light bg-light">
          <li>
            <%= link_to 'All Exercises', exercises_path %>
          </li>
        </nav>

        <nav class="navbar navbar-light bg-light">
          <li>
            <%= link_to 'New Workout', new_workout_path %>
          </li>
        </nav>

        <nav class="navbar navbar-light bg-light">
          <li>
            <%= link_to 'All Types', types_path %>
          </li>
        </nav>

        <nav class="navbar navbar-light bg-light">
          <li>
            <%= link_to 'Assign Workout to user', new_users_workout_path %>
          </li>
        </nav>
      <% end -%>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

<nav class="navbar navbar text-white h4">
  <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>  
    </li>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path) %> 
    </li>
  <% end %>
</nav>

<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <h1>Listing Workouts</h1>
</nav>
<table>
  <tr>
    <th>Title</th>  
    <th>Text</th>
    <th>Exercises</th>
    <th colspan="3"></th>
  </tr>  
  <% @workout.each do |workout| %>
    <tr>
      <td><%= workout.name %></td>
      <td><%= workout.description %></td>
       <td> <% workout.exercises.each do |ex| %>
          <%= ex.name %>
        <% end %></td>
      <td><%= link_to 'Show', workout_path(workout) %></td>
      <%if current_user.admin? %>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout_path(workout),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
                
        </td>
      <%end%>
    </tr>
  <% end %>
</table>
<%= will_paginate @workout %>

app/views/workouts/new.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <h1>New Workout</h1>
</nav>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @workout.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @workout.description %>
</p>

<p> 
  <% @workout.exercises.each do |ex| %>
    <li> 
      <%= ex.name %> 
      <%= video_tag url_for(ex.video), size: '150x150', :controls => true if ex.video.attached? %>
      <% ex.types.each do |ty| %>
        <%= ty.name %>
      <% end -%>
    </li>
  <% end %>
    
</p>

<%= link_to 'Back', workouts_path %>